[package]
name = "vmd-server"
version = "0.1.0"
edition = "2021"
authors = ["Ville Ilvonen <ville.ilvonen@unikie.com>", ]

[dependencies]
kvm-ioctls = { version = "0.12.0" }
rocket = { version = "0.5.0-rc.1", features = ["tls", "json"] }
thiserror = "1.0.38"
